### ISSUE TITLE
Build is currently broken - compilation error

### ISSUE THREAD

**Issue by jimitndiaye** [OrchardCMS/Orchard2#129]
C:\Dev\Orchard2\src\Orchard.DependencyInjection\ServiceProviderExtensions.cs(38,42): DNXCore,Version=v5.0 error CS1061: 'IServiceCollection' does not contain a definition for 'AddInstance' and no extension method 'AddInstance' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

Build failed.

This is while trying to build master https://github.com/OrchardCMS/Orchard2/commit/2bf3b4a640a2bc806e6cc4f9ae502e639aeef039

**Comment by GVX111** [comment]
Use dnx 1.0.0-rc1-final or 1.0.0-rc1-update1

**Comment by jimitndiaye** [comment]
Thanks for your help but unfortunately that didn't resolve it - still getting the same compilation error when using 1.0.0-rc1-update1.
This was a fresh clone of the latest master if that helps: 
C:\Dev\Orchard2>dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-16231   clr     x86          win
       1.0.0-rc1-16231   coreclr x86          win
  *    1.0.0-rc1-update1 clr     x86          win             default

**Comment by jimitndiaye** [comment]
Same thing happens when I install and select rc1-final: 
```

C:\Dev\Orchard2\src\Orchard.DependencyInjection\ServiceProviderExtensions.cs(38,42): DNXCore,Version=v5.0 error CS1061: 'IServiceCollection' does not contain a definition for 'AddInstance' and no extension method 'AddInstance' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

Build failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.6168964
Total build time elapsed: 00:00:00.6221667
Total projects built: 1
fail: Exit code 1 from cmd
fail: Stack trace:
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.Dnu(String command) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 477
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.DnuPack(String projectFile, String kpmPackOutputDir, String configuration) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 2537
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<>c__DisplayClass127.<RenderViewLevel0>b__d7(String projectFile) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 10710
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<>c__DisplayClass127.<RenderViewLevel0>b__d5() in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 10710
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.StartingTarget(String name) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 3742
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<RenderViewLevel0>b__89() in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 4339
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.StartingTarget(String name) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 3742
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<RenderViewLevel0>b__8a() in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 4356
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.StartingTarget(String name) in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 3742
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<RenderViewLevel0>b__8b() in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 4373
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewdfa4dfc5ca1d48ae8ec4b9108fd35cbf.<RenderViewLevel0>b__83() in c:\Users\<user>\AppData\Local\Temp\a027928f2add4a1da0ee8a013f6481c9-1.cs:line 4229
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

C:\Dev\Orchard2>dnvm list

Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-16231   clr     x86          win
       1.0.0-rc1-16231   coreclr x86          win
  *    1.0.0-rc1-final   clr     x86          win
       1.0.0-rc1-final   coreclr x86          win
       1.0.0-rc1-update1 clr     x64          win
       1.0.0-rc1-update1 clr     x86          win             default
       1.0.0-rc1-update1 coreclr x64          win
       1.0.0-rc1-update1 coreclr x86          win
```

**Comment by alexbocharov** [comment]
1. Clean %userprofile%\.dnx\packages and remove other runtimes (%userprofile%\.dnx\runtimes)
2. dnvm use 1.0.0-rc1-update1 -r coreclr -a x64
3. dnu restore

**Comment by GVX111** [comment]
ok u can change in project.json -> * to -rc1-final only for microsoft
ex: "Microsoft.AspNet.Server.WebListener": "1.0.0-*" to -> "Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-final"

**Comment by jimitndiaye** [comment]
Thank you. I did notice that I was getting a number of warnings that dependencies were resolving to rc2 versions

**Comment by GVX111** [comment]
Please close Issue if you fixed

**Comment by jimitndiaye** [comment]
Applying both suggested solutions fixed the problem for me.
