### ISSUE TITLE
Problem deploying Orchard 2

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#614]
I can execute without problems Orchard from VS2017 or calling `dotnet run` from `D:\Orchard2\src\Orchard.Cms.Web`. It responds to requests without throw any exception.

If I deploy orchard calling `run dotnet publish --configuration Release --output d:\OrchardDeploy`
I call `dotnet OrchardCore.Cms.dll` from `d:\OrchardDeploy` and Orchard apparently runs properly. 
However, for any request I receive following exception:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL3CBASSC1JT": An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddRouting' inside the call to 'ConfigureServices(...)' in the application startup code.
   at Microsoft.AspNetCore.Routing.RouteBuilder..ctor(IApplicationBuilder applicationBuilder, IRouter defaultHandler)
   at Microsoft.AspNetCore.Modules.ModularTenantRouteBuilder.Build() in D:\PROYECTOS\OrchardCMS\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouteBuilder.cs:line 27
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(ShellSettings shellSettings, IServiceProvider serviceProvider) in D:\PROYECTOS\OrchardCMS\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 90
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in D:\PROYECTOS\OrchardCMS\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__5.MoveNext() in D:\PROYECTOS\OrchardCMS\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantContainerMiddleware.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```
Before the upgrade to VS2017 of Orchard I was able to deploy it in this way without problems. But after VS2017 upgrade of Orchard cproj files it doesn't work

**Comment by sebastienros** [comment]
@jtkech have you had the issue on your side?
@Jetski5822 any idea?

**Comment by jersiovic** [comment]
This explains what happen:
![image](https://cloud.githubusercontent.com/assets/4950766/24007852/2527b2b6-0a70-11e7-97cc-6cfc46ef4b0b.png)
When app is published dlls are flattened at root folder of the app and no folder with dlls or manifest are published. However Orchard is looking for manifests in folders.
Copying Themes and Modules in the folder where I published the app it works properly.
So, we need a way to create the folders structure when the app is published

**Comment by sebastienros** [comment]
Great, exactly what @jtkech is working on right now. 

Can you try to add this file in the modules folder and rebuid/publish to see if that fixes everything?

https://github.com/OrchardCMS/Orchard2/blob/b7cc8bee80dfa3bc4e4422a2cb228c8fb185e684/src/Orchard.Cms.Web/Modules/Directory.Build.props

**Comment by jtkech** [comment]
Yes i know, they were published through project.json but not yet done since we migrated to csproj.

About the above file, it's a shared project part but only intended to be used for packaging purpose.

So, for publishing we just need to update the csproj file by using globbing patterns to define the assets we want to publish and by applying on them `CopyToPublishDirectory`.

**I will do it soon**, maybe through a separate PR or through the packages branch because we first want to see what we need to output on the build process, this when we use modules as project references but also as package references. This because assets which are part of the build are naturally outputed when publishing.

Best.

**Comment by jtkech** [comment]
Quickly done so it will be updated.

Just tried `dotnet OrchardCore.Cms.dll` from the published directory, seems to work.

It also works for a testing `HelloWorld` module referenced as a package.

So, meanwhile you can grab from the **packages branch** in `OrchardCore.Cms.csproj` the item group which is just before all project references.

Best.

**Comment by sebastienros** [comment]
Can you add a PR to master instead with this only fix?
