### ISSUE TITLE
Access token issued by refresh flow seems to be not valid

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#620]
After update oauth2 branch from alpha to beta version of OpenIddict refresh flow seems to be broken.

I get an access token and a refresh token using Password Grant
![image](https://cloud.githubusercontent.com/assets/4950766/24039880/1820a04a-0b07-11e7-89dd-11ae26f776d2.png)

I use that access token as bearer token to access web api controller protected by [Authorize] annotation without problems.
I use refresh flow to get another valid token using the original refresh token.
Apparently it works properly, however the new access token is not valid, because when it used as bearer token for requesting resources of the web api I get the following exception:

```
017-03-17 11:48:13.6471|1|Microsoft.AspNetCore.Server.Kestrel|DEBUG|Connection id "0HL3CLBH705TV" started. 
2017-03-17 11:48:13.6631|1|Microsoft.AspNetCore.Hosting.Internal.WebHost|INFO|Request starting HTTP/1.1 POST https://webapi.pccomb2b.pedidosinternet.com/PCCOM.Distrib.WebAPI.WebOrderNotes/B2BOrderNotes application/json 1627 
2017-03-17 11:48:13.6751|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.6902|0|Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware|INFO|Begin Routing Request 
2017-03-17 11:48:13.7132|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7232|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7232|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7412|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7412|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7592|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7683|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7683|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7862|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.7862|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.8043|1|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|DEBUG|POST requests are not supported 
2017-03-17 11:48:13.8133|7|AspNet.Security.OAuth.Validation.OAuthValidationMiddleware|INFO|Bearer was not authenticated. Failure message: Authentication failed because the access token was not valid for this resource server. 
2017-03-17 11:48:13.8133|1|Microsoft.AspNetCore.Routing.RouteBase|DEBUG|Request successfully matched the route with name 'B2BOrderNotes_Create' and template 'PCCOM.Distrib.WebAPI.WebOrderNotes/B2BOrderNotes'. 
2017-03-17 11:48:13.8323|1|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|DEBUG|Executing action PCCOM.Distrib.WebAPI.WebOrderNotes.Controllers.B2BOrderNotesController.Create (PCCOM.Distrib.WebAPI.WebOrderNotes) 
2017-03-17 11:48:13.8323|1|Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder|DEBUG|Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2017-03-17 11:48:13.8513|1|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|INFO|Executing action method PCCOM.Distrib.WebAPI.WebOrderNotes.Controllers.B2BOrderNotesController.Create (PCCOM.Distrib.WebAPI.WebOrderNotes) with arguments (PCCOM.Distrib.WebAPI.Core.Models.ClientDevice, PCCOM.Distrib.WebAPI.WebOrderNotes.DTOs.CreateB2BOrderContext) - ModelState is Valid 
2017-03-17 11:48:13.8513|2|Microsoft.AspNetCore.Authorization.DefaultAuthorizationService|INFO|Authorization failed for user: (null). 
2017-03-17 11:48:13.8693|0|PCCOM.Distrib.WebAPI.WebOrderNotes.Controllers.OrderNotesController|WARN|Forbidden to create a B2B order note for user (null) 
2017-03-17 11:48:13.8783|2|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|DEBUG|Executed action method PCCOM.Distrib.WebAPI.WebOrderNotes.Controllers.B2BOrderNotesController.Create (PCCOM.Distrib.WebAPI.WebOrderNotes), returned result Microsoft.AspNetCore.Mvc.ForbidResult. 
2017-03-17 11:48:13.8783|1|Microsoft.AspNetCore.Mvc.ForbidResult|INFO|Executing ForbidResult with authentication schemes (). 
2017-03-17 11:48:13.8973|13|AspNet.Security.OAuth.Validation.OAuthValidationMiddleware|INFO|AuthenticationScheme: Bearer was forbidden. 
2017-03-17 11:48:13.9083|2|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|INFO|Executed action PCCOM.Distrib.WebAPI.WebOrderNotes.Controllers.B2BOrderNotesController.Create (PCCOM.Distrib.WebAPI.WebOrderNotes) in 67.4515ms 
2017-03-17 11:48:13.9083|7|AspNet.Security.OAuth.Validation.OAuthValidationMiddleware|INFO|Bearer was not authenticated. Failure message: Authentication failed because the access token was not valid for this resource server. 
2017-03-17 11:48:13.9323|1|Microsoft.AspNetCore.Routing.RouteBase|DEBUG|Request successfully matched the route with name 'Diagnostics.Error' and template 'Error'. 
2017-03-17 11:48:13.9433|1|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|DEBUG|Executing action Orchard.Diagnostics.Controllers.DiagnosticsController.Error (Orchard.Diagnostics) 
2017-03-17 11:48:13.9553|1|Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter|INFO|Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present. The required antiforgery header value "RequestVerificationToken" is not present. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "RequestVerificationToken" is not present.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()     at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
2017-03-17 11:48:13.9703|1|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|INFO|Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter'. 
2017-03-17 11:48:13.9703|1|Microsoft.AspNetCore.Mvc.StatusCodeResult|INFO|Executing HttpStatusCodeResult, setting HTTP status code 400 
2017-03-17 11:48:13.9880|2|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|INFO|Executed action Orchard.Diagnostics.Controllers.DiagnosticsController.Error (Orchard.Diagnostics) in 38.9706ms 
2017-03-17 11:48:14.0036|9|Microsoft.AspNetCore.Server.Kestrel|DEBUG|Connection id "0HL3CLBH705TV" completed keep alive response. 
2017-03-17 11:48:14.0192|2|Microsoft.AspNetCore.Hosting.Internal.WebHost|INFO|Request finished in 356.4316ms 400  
```

**Comment by jersiovic** [comment]
@PinpointTownes this sounds me familiar, sth similar happened time ago because there was a bug in TokenStore

**Comment by jersiovic** [comment]
Still not sure if this is the only thing is causing problems but I see here sth that looks like a bug https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Migrations.cs#L17
`.Column<int>(nameof(OpenIdTokenIndex.Subject))`
should be
`.Column<string>(nameof(OpenIdTokenIndex.Subject))`

**Comment by PinpointTownes** [comment]
Here's the relevant error:

> 2017-03-17 11:48:13.9083|7|AspNet.Security.OAuth.Validation.OAuthValidationMiddleware|INFO|Bearer was not authenticated. Failure message: Authentication failed because the access token was not valid for this resource server. 

I took a brief look and it's indeed a bug, caused by this line: https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Controllers/AccessController.cs#L520

It should be included in the `if` block instead (because otherwise, it always overrides the resources stored in the refresh token by the resources specified in the refresh token request. If no resource is specified, this later fails when validating the audiences, as no resource was specified).

I'll fix it.

**Comment by jersiovic** [comment]
Oh great! this problem was driving me crazy

**Comment by PinpointTownes** [comment]
@jersiovic issue fixed?

**Comment by jersiovic** [comment]
yes
