### ISSUE TITLE
Unable to find the required services

### ISSUE THREAD

**Issue by kerryjiang** [OrchardCMS/Orchard2#708]
My environment is
OS: osx Sierra 10.12.4
dotnet version: 1.0.1

The website can be started successfully, but when I visited http://localhost:5000, I got the error below:

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL46T72TAFT2": An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddRouting' inside the call to 'ConfigureServices(...)' in the application startup code.
   at Microsoft.AspNetCore.Routing.RouteBuilder..ctor(IApplicationBuilder applicationBuilder, IRouter defaultHandler)
   at Microsoft.AspNetCore.Modules.ModularTenantRouteBuilder.Build() in /Users/kerryjiang/WorkShop/orchard/master/src/OrchardCore/Microsoft.AspNetCore.Modules/ModularTenantRouteBuilder.cs:line 23
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(ShellSettings shellSettings, IServiceProvider serviceProvider) in /Users/kerryjiang/WorkShop/orchard/master/src/OrchardCore/Microsoft.AspNetCore.Modules/ModularTenantRouterMiddleware.cs:line 97
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in /Users/kerryjiang/WorkShop/orchard/master/src/OrchardCore/Microsoft.AspNetCore.Modules/ModularTenantRouterMiddleware.cs:line 72

BTW, I did this change https://github.com/OrchardCMS/Orchard2/pull/707 to fix he building error.

**Comment by jtkech** [comment]
I assume you use the command line. Which command and from which folder? Because in your trace it seems that this is the `ModularTenantRouteBuilder.Build()` from `Microsoft.AspNetCore.Modules` which is used, not the one coming from `Orchard.Mvc.Core`.

Does it work if you use your own fix #703 ? I will take a look this night

**Comment by kerryjiang** [comment]
Yes, I used "dotnet run" in the src\Orchard.Cms.Web to start the website.
The build was successfully with my fix.

Does the running website use the resources in the folder?
If yes, I have to tell the website where it is?

**Comment by jtkech** [comment]
So, i think you mean that your fix also solves the building errors but doesn't solve this issue, right?

With your fix, i think modules assets are correctly stored in your temp folder. But, because the Temp folder is also used in `AsBundle.targets`, they are not copied under the main app directory.

This would explain that the startup of the `Orchard.Mvc` module is not executed and then that the correct route builder service is not registered.

But i want to understand why it is the same for you with my fix because it works well on my side, even through the command line.

Can you check if, after building, you get an `Orchard.Cms.Web\Packages` folder and what's in this folder.

Best.

**Comment by kerryjiang** [comment]
Cool, thanks!
This has been fixed by your RP: https://github.com/OrchardCMS/Orchard2/pull/707
