### ISSUE TITLE
Publish fails

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#756]
I have checked out head of master branch, then executed:
`git clean -df`
`dotnet restore`
`dotnet build`
`dotnet publish --configuration Release --output d:\WebAPI`

Dotnet build works properly, but publish step returns following error after Packaging asset files steps:
```
  Packaging asset files: TheTheme
  Can not find compilation library location for package 'markdig'
     at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
     at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
     at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
     at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
     at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
     at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
     at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.CompileViews(ViewCompilationInfo[] results, String assemblyname)
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
C:\Users\Sergio\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\netcoreapp1.1\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(25,5): error MSB3073: The command "dotnet exec --runtimeconfig "D:\PROYECTOS\OrchardCMS\Orchard2\src\Orchard.Cms.Web\bin\Release\netcoreapp1.1\Orchard.Cms.Web.runtimeconfig.json" --depsfile "D:\PROYECTOS\OrchardCMS\Orchard2\src\Orchard.Cms.Web\bin\Release\netcoreapp1.1\Orchard.Cms.Web.deps.json" "C:\Users\Sergio\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp1.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [D:\PROYECTOS\OrchardCMS\Orchard2\src\Orchard.Cms.Web\Orchard.Cms.Web.csproj]
```

The markdig dependency is from Orchard.Markdown module and it looks ok. In fact project can be executed without problems from VS2017. Any idea of waht could be happening?

**Comment by jtkech** [comment]
Just tried and it works on my side.

- In your trace the problem seems to occurs during view precompilation.

- But for me it works through vs2017 and also from the cli. Note: For testing i have a nightly built version of dotnet `2.0.0-preview2-006080` which is not used by vs2017, but which is used from the cli, so ...

- This by doing `dotnet restore` under `Orchard2` and `dotnet publish` under `Orchard.Cms.Web`. Note: here, no need to use `dotnet build` which would uses `config = Debug` by default.

- Maybe a problem during `dotnet restore`, i don't know because i couldn't repro.

**Comment by jersiovic** [comment]
`git clean -xdf` in place of `git clean -df` was what did the magic.
Now it works
Thank you
