### ISSUE TITLE
Orchard.OpenId access to signing cert's private key on Windows Server / IIS

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard2#827]
I'm not 100% sure if this is the recommended action, but we needed to give Read access to the Private Key of the **signing certificate** to the AppPool Identity on Windows Server / IIS.

_Note that we started of with Full Control but have since reduced that to Read._

The cert was generated with PS `New-SelfSignedCertificate`.

If this is the recommended action, perhaps this is worth noting in the **README.md** for the Orchard.OpenId module.

Giving access to the AppPool Identity to the Private Key can be achieved in various ways, e.g.:

- MMC Certificate Snap-In (Right-Click on the Cert, All tasks > Manage private key > Add IIS AppPool\AppPoolName with Read access,
- winhttpcertcfg.exe 

Not doing so produced a 500 result and the following log entries:

~~~~
2017-06-15 07:56:35.0020|None|0HL5JOG5KGC5Q|59|Microsoft.Extensions.DependencyInjection.DataProtectionServices|WARN|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2017-06-15 07:56:35.1259|None|0HL5JOG5KGC5Q|50|Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|WARN|Using an in-memory repository. Keys will not be persisted to storage. 
2017-06-15 07:56:37.7352|Default|0HL5JOG5KGC5Q|59|Microsoft.Extensions.DependencyInjection.DataProtectionServices|WARN|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2017-06-15 07:56:37.7523|Default|0HL5JOG5KGC5Q|50|Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|WARN|Using an in-memory repository. Keys will not be persisted to storage. 
2017-06-15 07:56:38.8003|Default|0HL5JOG5KGC5Q|0|Orchard.OpenId.OpenIdConfiguration|ERROR|An error occurred while trying to register a X.509 certificate. 
2017-06-15 07:56:38.9227|Default|0HL5JOG5KGC5Q|13|Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HL5JOG57HEGH": An unhandled exception was thrown by the application. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_HasPrivateKey()
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddKey(IList`1 credentials, SecurityKey key)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, X509Certificate2 certificate)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, String thumbprint, StoreName name, StoreLocation location)
   at Orchard.OpenId.OpenIdConfiguration.Configure(OpenIddictOptions options) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore.Modules\Orchard.OpenId\Services\OpenIdConfiguration.cs:line 54
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddict(IApplicationBuilder app)
   at Orchard.OpenId.Startup.Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore.Modules\Orchard.OpenId\Startup.cs:line 54
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(ShellSettings shellSettings, IServiceProvider serviceProvider) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 105
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantContainerMiddleware.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()    at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_HasPrivateKey()
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddKey(IList`1 credentials, SecurityKey key)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, X509Certificate2 certificate)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, String thumbprint, StoreName name, StoreLocation location)
   at Orchard.OpenId.OpenIdConfiguration.Configure(OpenIddictOptions options) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore.Modules\Orchard.OpenId\Services\OpenIdConfiguration.cs:line 54
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddict(IApplicationBuilder app)
   at Orchard.OpenId.Startup.Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore.Modules\Orchard.OpenId\Startup.cs:line 54
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(ShellSettings shellSettings, IServiceProvider serviceProvider) in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 105
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouterMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in D:\Repos\GH\zumeymedia\Orchard2\src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantContainerMiddleware.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-06-15 07:57:18.5309|Default|0HL5JOG5KGC5R|35|Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|No XML encryptor configured. Key {c2467ae9-ec5a-4799-a3dc-5aeea0cf9ad9} may be persisted to storage in unencrypted form. 
2017-06-15 07:57:22.9585|Default|0HL5JOG5KGC5S|35|Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|No XML encryptor configured. Key {36399eae-7155-4184-a16c-aee75b7035ac} may be persisted to storage in unencrypted form. 
2017-06-15 07:57:22.9872|Default|0HL5JOG5KGC5S|7|Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery|ERROR|An exception was thrown while deserializing the token. System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {cb5a586d-969e-4e61-884a-259677f15430} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
~~~~

**Comment by PinpointTownes** [comment]
> If this is the recommended action, perhaps this is worth noting in the README.md for the Orchard.OpenId module.

That's indeed exactly the right thing do to :+1: 

> If this is the recommended action, perhaps this is worth noting in the README.md for the Orchard.OpenId module.

Sounds like a good idea. Feel free to submit a PR to fix that :clap: 

Thanks!

**Comment by anoordende** [comment]
Superb, I will put a PR together.
