### ISSUE TITLE
error with orchardcore-preview build 2561 

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/Orchard2#857]
Hi, I upgraded a test app from Version="2.0.0-preview-2518" to Version="2.0.0-preview-2561"
and the cms does not start. (this also happens from 2555 to 2556, if you downgrade to a version <=2555 it works)

The following error occurs

orchard> fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL5UTANOASC6": An unhandled exception was thrown by the application.
System.InvalidOperationException: Could not resolve feature for type AdminController
   at Orchard.Environment.Extensions.TypeFeatureProvider.GetFeatureForDependency(Type dependency)
   at Orchard.Mvc.ModularApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.GetCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orchard.DeferredTasks.DeferredTaskMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by MichaelPetrinolis** [comment]
Hi, some more info and steps to reproduce.

1) Create a new Webapplication and add OrchardCore.CMS package.
2) Make the changes needed to add OrchardCMS and UseModules
3) Run, the error appears.

If you add Orchard.Queries as a nugget dependency to the WebApplication, the app starts.
This behavior exists after 2518 build

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/Orchard2/commit/f95533724d3ab35d68fc5f770116a6fe4656cd4b

**Comment by jtkech** [comment]
I will take a look when i have time.

That said @MichaelPetrinolis mentioned `Orchard.Queries` and, in `OrchardCore.Cms.csproj`, this is the only one for which `PrivateAssets="none"` is not specified.

Maybe not the root cause regarding the commit dates ...

But this could explain that the bluid counterpart of `Orchard.Queries` would not be executed when indirectly referenced through the bundle (assets would not be copied, e.g the manifest file), but would be when referenced through the web app directly.

I also saw that in `Orchard.Queries.csproj` and `Orchard.Lucene.csproj` there are useless `ItemGroup` defining individual asset `PackagePath` which are normally globaly defined in `AsModule.props`.

**Comment by jrestall** [comment]
I thought I'd take a look since my commit got referenced, although my initial thinking is that it wouldn't be related since the ShellContainerFactory change deals with Startup features and this error is caused by an AdminController feature not being found, which is the responsibility of ExtensionManager to add to TypeFeatureProvider.

Anyway from what I can see if you change Line 21 in TypeFeatureProvider to log the full type name:

`throw new InvalidOperationException($"Could not resolve feature for type {dependency.**FullName**}");` 

It becomes clear that ExtensionManager is having issues loading Orchard.Queries since the exception is now:
```
System.InvalidOperationException: Could not resolve feature for type Orchard.Queries.Sql.Controllers.AdminController
```
If you look at the Packages folder in the website root, there is no Orchard.Queries folder and therefore my _guess_ is that ExtensionManager can't find Orchard.Queries' Module.txt to load the features for the module. MVC still loads the referenced assembly however and finds the controller via the automatic ApplicationPartManager which is why the error is originating from ModularApplicationModelProvider due to the mismatch of the controller being present without any feature metadata. 

So I would agree with @jtkech that there is something misconfigured in the project/nuget package of Orchard.Queries that is causing Module.txt to not be copied to the Packages folder.

My suggestions:
- Change TypeFeatureProvider to log the FullName of the type instead of just Name. This will make the responsible module clearer in the future if any fail to load.

- Check the project files of Orchard.Queries (and others) for inconsistencies.

- Remove the need for Module.txt files ;)

**Comment by jtkech** [comment]
I didn't take the time to try it because i would need to re-pack all the projects and use a local feed. So, it's better to update the repo through a PR.

But i think we only need to add `PrivateAssets="none"` for the `Orchard.Queries` package reference in `OrchardCore.Cms.csproj`. This as done for other modules references.

I'll do a PR.

**Comment by jrestall** [comment]
Thanks @jtkech , that does seem to be the difference.

If you look at orchardcore.cms.nuspec:

```
        <dependency id="Orchard.Queries" version="2.0.0-preview-2606" exclude="Build,Analyzers" />
        <dependency id="OrchardCore.AsBundle" version="2.0.0-preview-2606" include="All" />
        <dependency id="Orchard.Admin" version="2.0.0-preview-2606" include="All" />
        ...
```
The  exclude="Build,Analyzers" would block the 'build/netstandard1.6/Orchard.Queries.props' from being included and therefore not set the PackageAssetFiles variable which holds the files to copy to the Packages folder.

Feels good to find the root cause and not have it be my change!

**Comment by jtkech** [comment]
Exactly, don't worry ;)

**Comment by MichaelPetrinolis** [comment]
updated to v2.0.0-preview-2629, removed orchard.queries nuget package from host and works
