### ISSUE TITLE
Orchard.Mvc.Web Run Error

### ISSUE THREAD

**Issue by china-live** [OrchardCMS/Orchard2#916]
2017-08-16 09:49:18.8677||0HL7494108V6V:00000001|0|Orchard.Environment.Shell.Builders.ShellContextFactory|INFO|Creating shell context for tenant Default 
2017-08-16 09:49:19.0783||0HL7494108V6V:00000001|0|Orchard.Environment.Shell.ShellHost|ERROR|A tenant could not be started: Default System.AggregateException: One or more errors occurred. (Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.) ---> System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Orchard.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell.Abstractions\Builders\Extensions\ServiceProviderExtensions.cs:line 40
   at Orchard.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContainerFactory.cs:line 45
   at Orchard.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext() in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContextFactory.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orchard.Environment.Shell.Builders.ShellContextFactory.<Orchard-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext() in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContextFactory.cs:line 37
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Orchard.Environment.Shell.ShellHost.<>c__DisplayClass11_0.<GetOrCreateShellContext>b__0(String tenant) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 77
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Environment.Shell.ShellHost.GetOrCreateShellContext(ShellSettings settings) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 75
   at Orchard.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__13_0(ShellSettings settings) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 120
---> (Inner Exception #0) System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Orchard.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell.Abstractions\Builders\Extensions\ServiceProviderExtensions.cs:line 40
   at Orchard.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContainerFactory.cs:line 45
   at Orchard.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext() in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContextFactory.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orchard.Environment.Shell.Builders.ShellContextFactory.<Orchard-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext() in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\Builders\ShellContextFactory.cs:line 37<---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Orchard.Environment.Shell.ShellHost.<>c__DisplayClass11_0.<GetOrCreateShellContext>b__0(String tenant) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 77
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Environment.Shell.ShellHost.GetOrCreateShellContext(ShellSettings settings) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 75
   at Orchard.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__13_0(ShellSettings settings) in D:\Orchard\orchard2\src\OrchardCore\Orchard.Environment.Shell\ShellHost.cs:line 120
2017-08-16 09:49:19.1155||0HL7494108V6V:00000001|0|Orchard.Environment.Shell.ShellHost|INFO|Done creating shells

**Comment by china-live** [comment]
It has been resolved. You need to add the Microsoft.ApplicationInsights.AspNetCore package

**Comment by Jetski5822** [comment]
ARGH!!! I hit the same

**Comment by china-live** [comment]
supplement:
see https://www.visualstudio.com/en-us/news/releasenotes/vs2017-knownissues Application Insights Issues

**Comment by china-live** [comment]
The above methods are palliative
The last solution.
Adding services.AddSingleton (JavaScriptEncoder.Default) to Startup.ConfigureServices;
