### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK__Document__3214EC0705D23E33'. Cannot insert duplicate key in object 'dbo.Document'

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#970]
A strange error occurs when trying to create a new OpenID Connect app (`dev` branch, new setup, fresh new database):

```
System.AggregateException: One or more errors occurred. (Violation of PRIMARY KEY constraint 'PK__Document__3214EC0705D23E33'. Cannot insert duplicate key in object 'dbo.Document'. The duplicate key value is (82).
The statement has been terminated.) ---> System.Data.SqlClient.SqlException: Violation of PRIMARY KEY constraint 'PK__Document__3214EC0705D23E33'. Cannot insert duplicate key in object 'dbo.Document'. The duplicate key value is (82).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dapper.SqlMapper.<ExecuteScalarImplAsync>d__55`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<SaveEntityAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at YesSql.Session.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceScope.Dispose()
   at OrchardCore.Hosting.ShellBuilders.ShellContext.ServiceScopeWrapper.Dispose()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
---> (Inner Exception #0) System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__Document__3214EC0705D23E33'. Cannot insert duplicate key in object 'dbo.Document'. The duplicate key value is (82).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dapper.SqlMapper.<ExecuteScalarImplAsync>d__55`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<SaveEntityAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()
```

@sebastienros any idea?

**Comment by sebastienros** [comment]
Super weird, never got an issue like this outside of open id, will try that.
IT repros all the time?
SQL Server I assume?

**Comment by PinpointTownes** [comment]
> IT repros all the time?

All the time.

> SQL Server I assume?

Absolutely.

A important detail: no entry with the PK `82` is present in the database after seeing this error. I'm tempted to think that something in the pipeline tries to insert the entity twice, which causes an error when persisting the changes. A service lifetime issue?

**Comment by sebastienros** [comment]
Agreed, probably creating the document twice ... maybe yessql bug. In the UI you just go create a new app?
You are not double-clicking the OK button, even so it should not fail.

**Comment by PinpointTownes** [comment]
> In the UI you just go create a new app?

Yep.

> You are not double-clicking the OK button, even so it should not fail.

No double-clicking (Fiddler confirms that only one request is sent).

**Comment by sebastienros** [comment]
Can't repro, tried with Sqlite and Sqlserver. Design -> Security -> Apps, create new one.

**Comment by sebastienros** [comment]
I don't have you latest changes though.

**Comment by sebastienros** [comment]
Fixed in dev

**Comment by PinpointTownes** [comment]
Arf, sorry for that :cry:  

Could you please directly fix that in the dev branch? It will be easier than sending a PR :smile:

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/OrchardCMS/Orchard2/commit/af3ceae4ba3c946f44a1d27d35efa681f656f6a2.

Thanks @sebastienros :smile:
